# 監視銘柄リスト
tickers:
  - AAPL
  - ALAB
  - AMAT
  - AMD
  - AMZN
  - APP
  - ASTS
  - AVAV
  - BBAI
  - BSY
  - CAKE
  - CART
  - CEG
  - CELH
  - COHR
  - CRM
  - CRWV
  - CSGP
  - DDOG
  - ELF
  - ESTC
  - GOOGL
  - GTLB
  - IONQ
  - IOT
  - JOBY
  - KO
  - LITE
  - LLY
  - LMT
  - META
  - MRVL
  - MSFT
  - NET
  - NOW
  - NVDA
  - ONDS
  - PLTR
  - QBTS
  - RBRK
  - RCAT
  - RDW
  - RKLB
  - RXRX
  - S
  - SITM
  - SOFI
  - SOUN
  - SPIR
  - TSLA
  - VRT
  - ZETA
  - ZS
  - ADBE
  - ADSK
  - BKNG
  - CDNS
  - CIX
  - CPRT
  - DOCN
  - FCX
  - FICO
  - FRSH
  - HEI
  - HON
  - HQY
  - HWM
  - INTU
  - KULR
  - MSCI
  - PAYS
  - SCCO
  - TASK
  - TDY
  - V
  - VST
  - ABBV
  - BROS
  - CAT
  - DELL
  - FLYW
  - FROG
  - GEV
  - JNJ
  - LOAR
  - LYFT
  - MO
  - PEP
  - PM
  - SNPS
  - VZ
  - WMT
  - XOM
  - RMBS
  - ENTG
  - TER
  - KLAC
  - LRCX
